#Import libraries

In [12]:
import pandas as pd
import numpy as np

#from scipy.stats import chi2_contingency
import scipy.stats as ss
from sklearn.preprocessing import LabelEncoder

In [19]:
#from statsmodels.stats.power import TTestIndPower
#from matplotlib import pyplot

#PowerAns = TTestIndPower()
#effect_sizes = np.array([0.25, 0.95])
#sample_sizes = np.array(range(100, 10000))
#PowerAns.plot_power(dep_var = 'nobs', nobs = sample_sizes, effect_size = effect_sizes) #es is effect size
#pyplot.xlabel('Sample datasize') 
#pyplot.ylabel('Power')
#pyplot.title('Power curve')
#pyplot.grid()
#pyplot.show()

In [13]:
le = LabelEncoder()

In [1]:
#df = pd.read_csv('Interaction+demography+payor.csv')
#df.info()

In [5]:
#df.count()
#df.head(5)

#df['date of interaction'].max() 
##Data till May-2022

In [2]:
#df[['service', 'gender', 'age','payor','enrolled_channel']] = df[['service', 'gender', 'age','payor','enrolled_channel']].apply(le.fit_transform)
#df.head(5)


AGE & SERVICE

In [3]:
#data = df.sample(n = 9000, random_state = 1)

#contingency_table = pd.crosstab(data['age'], data['service']) #observed frequency
#results = ss.chi2_contingency(contingency_table) #stat, p, dof, expected freq. 
#results                                          #p-value<5%

In [4]:
#ss.chi2_contingency(contingency_table, lambda_ = "log-likelihood") #checking with method other than Pearson chi-square


GENDER & SERVICE

In [5]:
#data1 = df.sample(n = 9000, random_state = 1)

#contingency_table = pd.crosstab(data1['gender'], data1['service']) #observed frequency
#results = ss.chi2_contingency(contingency_table) #stat, p, dof, expected freq. 
#results                                          #p-value<5%

In [6]:
#ss.chi2_contingency(contingency_table, lambda_ = "log-likelihood")

PAYOR & SERVICE

In [7]:
#data2 = df.sample(n = 9000, random_state = 1)

#contingency_table = pd.crosstab(data2['payor'], data2['service']) #observed frequency
#results = ss.chi2_contingency(contingency_table) #stat, p, dof, expected freq. 
#results #p-value<5%

In [8]:
#ss.chi2_contingency(contingency_table, lambda_ = "log-likelihood")

ENROLLED CHANNEL & SERVICE

In [9]:
#data3 = df.sample(n = 9000, random_state = 1)

#contingency_table = pd.crosstab(data3['enrolled_channel'], data3['service']) #observed frequency
#results = ss.chi2_contingency(contingency_table) #stat, p, dof, expected freq. 
#results #p-value<5%

In [10]:
#ss.chi2_contingency(contingency_table, lambda_ = "log-likelihood")

Age, gender, payor, enrolled channel and service are dependent variables as p-value <= 5% 

In [18]:
df1 = pd.read_csv('Interaction+Email.csv')
df1.info()

C:\Users\RanjaSarkar\AppData\Local\Temp\ipykernel_24404\3903274542.py:1: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('Interaction+Email.csv')


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2885871 entries, 0 to 2885870
Data columns (total 13 columns):
 #   Column               Dtype  
---  ------               -----  
 0   patient_id           int64  
 1   service              object 
 2   date of interaction  object 
 3   account_record_type  object 
 4   HCP type             object 
 5   enrollment_status    object 
 6   Months on program    float64
 7   Months on therapy    float64
 8   sent_date            object 
 9   status               object 
 10  total_opens          float64
 11  opened               int64  
 12  territory            object 
dtypes: float64(3), int64(2), object(8)
memory usage: 286.2+ MB


In [19]:
df1.dropna(subset = ['Months on program', 'Months on therapy'], inplace = True)

In [ ]:
df1.drop(df1[df1["Months on program"] < 0].index, inplace = True)

In [23]:
df1.count()

patient_id             1807002
service                1807002
date of interaction    1807002
account_record_type    1807002
HCP type               1807002
enrollment_status      1807002
Months on program      1807002
Months on therapy      1807002
sent_date              1807002
status                 1807002
total_opens            1807002
opened                 1807002
territory              1807002
dtype: int64

In [21]:
#df1[['HCP type', 'enrollment_status', 'territory', 'Months on program', 'Months on therapy']].count()

In [24]:
df1[['service', 'HCP type', 'enrollment_status', 'territory']] = df1[['service', 'HCP type', 'enrollment_status', 'territory']].apply(le.fit_transform)
df1.head(5)

patient_id  service  date of interaction account_record_type  HCP type  \
448    20401322        2  2017-06-28 00:00:00               Adult         1   
449    20401322        4  2017-06-28 00:00:00               Adult         1   
450    20401322        4  2017-07-05 00:00:00               Adult         1   
451    20401322        8  2017-07-07 00:00:00               Adult         1   
452    20401322        0  2017-07-13 00:00:00               Adult         1   

     enrollment_status  Months on program  Months on therapy  \
448                  7               48.0               46.6   
449                  7               48.0               46.6   
450                  7               48.0               46.6   
451                  7               48.0               46.6   
452                  7               48.0               46.6   

               sent_date     status  total_opens  opened  territory  
448  2018-02-01 09:34:00  Delivered          2.0       1          0  
449  2018-02-01 09:34:00  Delivered          2.0       1          0  
450  2018-02-01 09:34:00  Delivered          2.0       1          0  
451  2018-02-01 09:34:00  Delivered          2.0       1          0  
452  2018-02-01 09:34:00  Delivered          2.0       1          0

HCP TYPE & SERVICE

In [25]:
data0 = df1.sample(n = 9000, random_state = 1)

contingency_table = pd.crosstab(data0['HCP type'], data0['service']) #observed frequency
results = ss.chi2_contingency(contingency_table) #stat, p, dof, expected freq. 
results                                          #p-value<5%

(88.71452153803102,
 1.692989620503771e-08,
 27,
 array([[4.38670222e+02, 8.91048889e+01, 2.59681556e+02, 1.85375556e+01,
         4.93815556e+01, 2.86319556e+02, 1.04371111e+01, 3.20902222e+01,
         2.15596444e+02, 2.18088889e+00],
        [1.65205333e+02, 3.35573333e+01, 9.77973333e+01, 6.98133333e+00,
         1.85973333e+01, 1.07829333e+02, 3.93066667e+00, 1.20853333e+01,
         8.11946667e+01, 8.21333333e-01],
        [1.02001778e+02, 2.07191111e+01, 6.03824444e+01, 4.31044444e+00,
         1.14824444e+01, 6.65764444e+01, 2.42688889e+00, 7.46177778e+00,
         5.01315556e+01, 5.07111111e-01],
        [2.11012267e+03, 4.28618667e+02, 1.24913867e+03, 8.91706667e+01,
         2.37538667e+02, 1.37727467e+03, 5.02053333e+01, 1.54362667e+02,
         1.03707733e+03, 1.04906667e+01]]))

In [26]:
ss.chi2_contingency(contingency_table, lambda_ = "log-likelihood")

(91.51935169232652,
 6.078071348276616e-09,
 27,
 array([[4.38670222e+02, 8.91048889e+01, 2.59681556e+02, 1.85375556e+01,
         4.93815556e+01, 2.86319556e+02, 1.04371111e+01, 3.20902222e+01,
         2.15596444e+02, 2.18088889e+00],
        [1.65205333e+02, 3.35573333e+01, 9.77973333e+01, 6.98133333e+00,
         1.85973333e+01, 1.07829333e+02, 3.93066667e+00, 1.20853333e+01,
         8.11946667e+01, 8.21333333e-01],
        [1.02001778e+02, 2.07191111e+01, 6.03824444e+01, 4.31044444e+00,
         1.14824444e+01, 6.65764444e+01, 2.42688889e+00, 7.46177778e+00,
         5.01315556e+01, 5.07111111e-01],
        [2.11012267e+03, 4.28618667e+02, 1.24913867e+03, 8.91706667e+01,
         2.37538667e+02, 1.37727467e+03, 5.02053333e+01, 1.54362667e+02,
         1.03707733e+03, 1.04906667e+01]]))

Enrollment Status & Service

In [29]:
dat0 = df1.sample(n = 10000, random_state = 1)

contingency_table = pd.crosstab(dat0['enrollment_status'], dat0['service']) #observed frequency
results = ss.chi2_contingency(contingency_table) #stat, p, dof, expected freq. 
results                                          #p-value<5%

(112.45219905070378,
 5.403364423691009e-06,
 54,
 array([[3.3244900e+01, 6.7838000e+00, 1.9816400e+01, 1.3803000e+00,
         3.8520000e+00, 2.1763800e+01, 8.0250000e-01, 2.4289000e+00,
         1.6756200e+01, 1.7120000e-01],
        [6.2140000e+00, 1.2680000e+00, 3.7040000e+00, 2.5800000e-01,
         7.2000000e-01, 4.0680000e+00, 1.5000000e-01, 4.5400000e-01,
         3.1320000e+00, 3.2000000e-02],
        [4.9712000e+00, 1.0144000e+00, 2.9632000e+00, 2.0640000e-01,
         5.7600000e-01, 3.2544000e+00, 1.2000000e-01, 3.6320000e-01,
         2.5056000e+00, 2.5600000e-02],
        [6.2140000e-01, 1.2680000e-01, 3.7040000e-01, 2.5800000e-02,
         7.2000000e-02, 4.0680000e-01, 1.5000000e-02, 4.5400000e-02,
         3.1320000e-01, 3.2000000e-03],
        [4.9090600e+01, 1.0017200e+01, 2.9261600e+01, 2.0382000e+00,
         5.6880000e+00, 3.2137200e+01, 1.1850000e+00, 3.5866000e+00,
         2.4742800e+01, 2.5280000e-01],
        [2.1127600e+01, 4.3112000e+00, 1.2593600e+01, 8.7720

In [30]:
ss.chi2_contingency(contingency_table, lambda_ = "log-likelihood")

(78.79823311803578,
 0.01547990364528948,
 54,
 array([[3.3244900e+01, 6.7838000e+00, 1.9816400e+01, 1.3803000e+00,
         3.8520000e+00, 2.1763800e+01, 8.0250000e-01, 2.4289000e+00,
         1.6756200e+01, 1.7120000e-01],
        [6.2140000e+00, 1.2680000e+00, 3.7040000e+00, 2.5800000e-01,
         7.2000000e-01, 4.0680000e+00, 1.5000000e-01, 4.5400000e-01,
         3.1320000e+00, 3.2000000e-02],
        [4.9712000e+00, 1.0144000e+00, 2.9632000e+00, 2.0640000e-01,
         5.7600000e-01, 3.2544000e+00, 1.2000000e-01, 3.6320000e-01,
         2.5056000e+00, 2.5600000e-02],
        [6.2140000e-01, 1.2680000e-01, 3.7040000e-01, 2.5800000e-02,
         7.2000000e-02, 4.0680000e-01, 1.5000000e-02, 4.5400000e-02,
         3.1320000e-01, 3.2000000e-03],
        [4.9090600e+01, 1.0017200e+01, 2.9261600e+01, 2.0382000e+00,
         5.6880000e+00, 3.2137200e+01, 1.1850000e+00, 3.5866000e+00,
         2.4742800e+01, 2.5280000e-01],
        [2.1127600e+01, 4.3112000e+00, 1.2593600e+01, 8.7720000

Enrollment Territory & Service

In [31]:
da0 = df1.sample(n = 9000, random_state = 1)

contingency_table = pd.crosstab(da0['territory'], da0['service']) #observed frequency
results = ss.chi2_contingency(contingency_table) #stat, p, dof, expected freq. 
results                                          #p-value<5%

(75.61988026715535,
 0.002873332446578163,
 45,
 array([[2.28064711e+03, 4.63256444e+02, 1.35008478e+03, 9.63767778e+01,
         2.56734778e+02, 1.48857578e+03, 5.42625556e+01, 1.66837111e+02,
         1.12088622e+03, 1.13384444e+01],
        [2.31224889e+02, 4.69675556e+01, 1.36879222e+02, 9.77122222e+00,
         2.60292222e+01, 1.50920222e+02, 5.50144444e+00, 1.69148889e+01,
         1.13641778e+02, 1.14955556e+00],
        [1.18584889e+02, 2.40875556e+01, 7.01992222e+01, 5.01122222e+00,
         1.33492222e+01, 7.74002222e+01, 2.82144444e+00, 8.67488889e+00,
         5.82817778e+01, 5.89555556e-01],
        [6.47680000e+01, 1.31560000e+01, 3.83410000e+01, 2.73700000e+00,
         7.29100000e+00, 4.22740000e+01, 1.54100000e+00, 4.73800000e+00,
         3.18320000e+01, 3.22000000e-01],
        [1.62702222e+01, 3.30488889e+00, 9.63155556e+00, 6.87555556e-01,
         1.83155556e+00, 1.06195556e+01, 3.87111111e-01, 1.19022222e+00,
         7.99644444e+00, 8.08888889e-02],
        [1.0

In [32]:
ss.chi2_contingency(contingency_table, lambda_ = "log-likelihood")

(72.11051935679481,
 0.006305645929797836,
 45,
 array([[2.28064711e+03, 4.63256444e+02, 1.35008478e+03, 9.63767778e+01,
         2.56734778e+02, 1.48857578e+03, 5.42625556e+01, 1.66837111e+02,
         1.12088622e+03, 1.13384444e+01],
        [2.31224889e+02, 4.69675556e+01, 1.36879222e+02, 9.77122222e+00,
         2.60292222e+01, 1.50920222e+02, 5.50144444e+00, 1.69148889e+01,
         1.13641778e+02, 1.14955556e+00],
        [1.18584889e+02, 2.40875556e+01, 7.01992222e+01, 5.01122222e+00,
         1.33492222e+01, 7.74002222e+01, 2.82144444e+00, 8.67488889e+00,
         5.82817778e+01, 5.89555556e-01],
        [6.47680000e+01, 1.31560000e+01, 3.83410000e+01, 2.73700000e+00,
         7.29100000e+00, 4.22740000e+01, 1.54100000e+00, 4.73800000e+00,
         3.18320000e+01, 3.22000000e-01],
        [1.62702222e+01, 3.30488889e+00, 9.63155556e+00, 6.87555556e-01,
         1.83155556e+00, 1.06195556e+01, 3.87111111e-01, 1.19022222e+00,
         7.99644444e+00, 8.08888889e-02],
        [1.0

HCP type, enrollment status, territory and service are dependent variables as p-value <= 5% 

In [32]:
#df1['Months on program'].isna().sum()
#df1[['Months on program', 'Months on therapy']].count()

In [33]:
from scipy.stats import f_oneway

In [50]:
dat = df1.sample(n = 100, random_state = 1)

In [51]:
f_oneway(dat['Months on therapy'], dat['service'])

F_onewayResult(statistic=28.905824192219058, pvalue=2.1273496871985865e-07)

In [52]:
f_oneway(dat['Months on program'], dat['service'])

F_onewayResult(statistic=423.37226169478055, pvalue=4.606632631280717e-51)

p-value <= 5% ==>> Reject NULL -->> Months on program & months on therapy and service are dependent  